services:
  postgres:
    image: postgres:18
    restart: unless-stopped
    environment:
      POSTGRES_USER: todoodle
      POSTGRES_PASSWORD: WSX6y4wP5nhwgLF
      POSTGRES_DB: todoodle
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/18/docker

volumes:
  postgres_data:
