/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppUpcomingRouteImport } from './routes/app/upcoming'
import { Route as AppTodayRouteImport } from './routes/app/today'
import { Route as AppReportingRouteImport } from './routes/app/reporting'
import { Route as AppInboxRouteImport } from './routes/app/inbox'
import { Route as AppFiltersLabelsRouteImport } from './routes/app/filters-labels'
import { Route as AppProjectsIndexRouteImport } from './routes/app/projects/index'
import { Route as AppProjectsIdRouteImport } from './routes/app/projects/$id'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppUpcomingRoute = AppUpcomingRouteImport.update({
  id: '/upcoming',
  path: '/upcoming',
  getParentRoute: () => AppRoute,
} as any)
const AppTodayRoute = AppTodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => AppRoute,
} as any)
const AppReportingRoute = AppReportingRouteImport.update({
  id: '/reporting',
  path: '/reporting',
  getParentRoute: () => AppRoute,
} as any)
const AppInboxRoute = AppInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AppRoute,
} as any)
const AppFiltersLabelsRoute = AppFiltersLabelsRouteImport.update({
  id: '/filters-labels',
  path: '/filters-labels',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsIndexRoute = AppProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsIdRoute = AppProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/app': typeof AppRouteWithChildren
  '/app/filters-labels': typeof AppFiltersLabelsRoute
  '/app/inbox': typeof AppInboxRoute
  '/app/reporting': typeof AppReportingRoute
  '/app/today': typeof AppTodayRoute
  '/app/upcoming': typeof AppUpcomingRoute
  '/app/': typeof AppIndexRoute
  '/app/projects/$id': typeof AppProjectsIdRoute
  '/app/projects/': typeof AppProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/app/filters-labels': typeof AppFiltersLabelsRoute
  '/app/inbox': typeof AppInboxRoute
  '/app/reporting': typeof AppReportingRoute
  '/app/today': typeof AppTodayRoute
  '/app/upcoming': typeof AppUpcomingRoute
  '/app': typeof AppIndexRoute
  '/app/projects/$id': typeof AppProjectsIdRoute
  '/app/projects': typeof AppProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/app': typeof AppRouteWithChildren
  '/app/filters-labels': typeof AppFiltersLabelsRoute
  '/app/inbox': typeof AppInboxRoute
  '/app/reporting': typeof AppReportingRoute
  '/app/today': typeof AppTodayRoute
  '/app/upcoming': typeof AppUpcomingRoute
  '/app/': typeof AppIndexRoute
  '/app/projects/$id': typeof AppProjectsIdRoute
  '/app/projects/': typeof AppProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/app'
    | '/app/filters-labels'
    | '/app/inbox'
    | '/app/reporting'
    | '/app/today'
    | '/app/upcoming'
    | '/app/'
    | '/app/projects/$id'
    | '/app/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/app/filters-labels'
    | '/app/inbox'
    | '/app/reporting'
    | '/app/today'
    | '/app/upcoming'
    | '/app'
    | '/app/projects/$id'
    | '/app/projects'
  id:
    | '__root__'
    | '/app'
    | '/app/filters-labels'
    | '/app/inbox'
    | '/app/reporting'
    | '/app/today'
    | '/app/upcoming'
    | '/app/'
    | '/app/projects/$id'
    | '/app/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/upcoming': {
      id: '/app/upcoming'
      path: '/upcoming'
      fullPath: '/app/upcoming'
      preLoaderRoute: typeof AppUpcomingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/today': {
      id: '/app/today'
      path: '/today'
      fullPath: '/app/today'
      preLoaderRoute: typeof AppTodayRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reporting': {
      id: '/app/reporting'
      path: '/reporting'
      fullPath: '/app/reporting'
      preLoaderRoute: typeof AppReportingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/inbox': {
      id: '/app/inbox'
      path: '/inbox'
      fullPath: '/app/inbox'
      preLoaderRoute: typeof AppInboxRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/filters-labels': {
      id: '/app/filters-labels'
      path: '/filters-labels'
      fullPath: '/app/filters-labels'
      preLoaderRoute: typeof AppFiltersLabelsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/projects/': {
      id: '/app/projects/'
      path: '/projects'
      fullPath: '/app/projects/'
      preLoaderRoute: typeof AppProjectsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/projects/$id': {
      id: '/app/projects/$id'
      path: '/projects/$id'
      fullPath: '/app/projects/$id'
      preLoaderRoute: typeof AppProjectsIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppFiltersLabelsRoute: typeof AppFiltersLabelsRoute
  AppInboxRoute: typeof AppInboxRoute
  AppReportingRoute: typeof AppReportingRoute
  AppTodayRoute: typeof AppTodayRoute
  AppUpcomingRoute: typeof AppUpcomingRoute
  AppIndexRoute: typeof AppIndexRoute
  AppProjectsIdRoute: typeof AppProjectsIdRoute
  AppProjectsIndexRoute: typeof AppProjectsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppFiltersLabelsRoute: AppFiltersLabelsRoute,
  AppInboxRoute: AppInboxRoute,
  AppReportingRoute: AppReportingRoute,
  AppTodayRoute: AppTodayRoute,
  AppUpcomingRoute: AppUpcomingRoute,
  AppIndexRoute: AppIndexRoute,
  AppProjectsIdRoute: AppProjectsIdRoute,
  AppProjectsIndexRoute: AppProjectsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
